"""Initial MySQL structure

Revision ID: 564ce34dd6a8
Revises: 
Create Date: 2026-07-18 13:59:38.062927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '564ce34dd6a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('MATCH', 'TRAINING', name='eventtypeenum'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('surname1', sa.String(length=100), nullable=False),
    sa.Column('surname2', sa.String(length=100), nullable=False),
    sa.Column('prefered_name', sa.String(length=100), nullable=True),
    sa.Column('pronouns', sa.Enum('HE_HIM', 'SHE_HER', 'THEY_THEM', 'OTHER', name='pronounsenum'), nullable=True),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', name='sexenum'), nullable=False),
    sa.Column('main_position', sa.Enum('SETTER', 'MIDDLE', 'OUTSIDE', 'OPPOSITE', 'LIBERO', name='positionenum'), nullable=False),
    sa.Column('secondary_position', sa.Enum('SETTER', 'MIDDLE', 'OUTSIDE', 'OPPOSITE', 'LIBERO', name='positionenum'), nullable=True),
    sa.Column('role', sa.Enum('PLAYER', 'COACH', name='userroleenum'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_hashed_password'), 'players', ['hashed_password'], unique=True)
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_username'), 'players', ['username'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.create_table('assistances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ASSISTING', 'NOT_ASSISTING', 'DONT_KNOW', name='assistancestatusenum'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistances_id'), 'assistances', ['id'], unique=False)
    op.create_table('event_teams',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'team_id')
    )
    op.create_table('player_teams',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'team_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_teams')
    op.drop_table('event_teams')
    op.drop_index(op.f('ix_assistances_id'), table_name='assistances')
    op.drop_table('assistances')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_players_username'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_index(op.f('ix_players_hashed_password'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
